site_name: Motorola G54/64 Guides
copyright: Copyright &copy; 2025 rvsmooth

nav:
  - Home: index.md
  - Bootloader Unlock: bl_unlock.md
  - Custom ROM Flashing: cr_flashing.md
  - Fix Empty Slots: fix_emptysl.md
  - Downgrade: downgrade.md
  - About: about.md

theme:
  name: 'material'
  palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - content.code.copy
  font:
    - false

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

