site_name: Motorola G54/64 Guides
copyright: Copyright &copy; 2025 rvsmooth

nav:
  - Home: index.md
  - Guides:
      - Bootloader Unlock: guides/bl_unlock.md
      - Custom ROM Flashing: guides/cr_flashing.md
  - About: about.md

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs

markdown_extensions:
  - attr_list
